version: '2'
services:
  config0:
    container_name: config0
    hostname: config0.vespa_default
    image: vespaengine/vespa
    command: configserver
    privileged: true
    environment:
      - VESPA_CONFIGSERVERS=config0.vespa_default,config1.vespa_default,config2.vespa_default
    ports:
      - "19071:19071"

  config1:
    container_name: config1
    hostname: config1.vespa_default
    image: vespaengine/vespa
    command: configserver
    privileged: true
    environment:
      - VESPA_CONFIGSERVERS=config0.vespa_default,config1.vespa_default,config2.vespa_default

  config2:
    container_name: config2
    hostname: config2.vespa_default
    image: vespaengine/vespa
    command: configserver
    privileged: true
    environment:
      - VESPA_CONFIGSERVERS=config0.vespa_default,config1.vespa_default,config2.vespa_default

  container0:
    container_name: container0 
    hostname: container0.vespa_default
    image: vespaengine/vespa
    command: services
    privileged: true
    environment:
      - VESPA_CONFIGSERVERS=config0.vespa_default,config1.vespa_default,config2.vespa_default
    ports:
      - "8080:8080"

  container1:
    container_name: container1 
    hostname: container1.vespa_default
    image: vespaengine/vespa
    command: services
    privileged: true
    environment:
      - VESPA_CONFIGSERVERS=config0.vespa_default,config1.vespa_default,config2.vespa_default

  container2:
    container_name: container2 
    hostname: container2.vespa_default
    image: vespaengine/vespa
    command: services
    privileged: true
    environment:
      - VESPA_CONFIGSERVERS=config0.vespa_default,config1.vespa_default,config2.vespa_default

  content0:
    container_name: content0
    hostname: content0.vespa_default
    image: vespaengine/vespa
    command: services
    privileged: true
    environment:
      - VESPA_CONFIGSERVERS=config0.vespa_default,config1.vespa_default,config2.vespa_default

  content1:
    container_name: content1
    hostname: content1.vespa_default
    image: vespaengine/vespa
    command: services
    privileged: true
    environment:
      - VESPA_CONFIGSERVERS=config0.vespa_default,config1.vespa_default,config2.vespa_default

  content2:
    container_name: content2
    hostname: content2.vespa_default
    image: vespaengine/vespa
    command: services
    privileged: true
    environment:
      - VESPA_CONFIGSERVERS=config0.vespa_default,config1.vespa_default,config2.vespa_default
